### ISSUE TITLE
스플래시 화면 리디자인

### ISSUE THREAD

**Issue by huiwoo-jo** [TeamDMU/DMU-Android#131]
## 🤔 목적

> 스플래시 화면 리디자인

## 📝 TO-DO

- [ ] 스플래시 배경 화면 색상 수정
- [ ] drawable 파일에 스플래시용 로고 등록

**Comment by hoyahozz** [comment]
관련 이슈 : #86

**Comment by huiwoo-jo** [comment]
이슈 중복으로 인한 투두 리스트 수정 완료했습니다!
