### ISSUE TITLE
바인딩 어댑터 정리

### ISSUE THREAD

**Issue by hoyahozz** [TeamDMU/DMU-Android#91]
## 🤔 목적

> 바인딩 어댑터 관련 코드 리팩터링

## 📝 TO-DO

- [ ] 개판 오분전인 코드 리팩터링

**Comment by m6z1** [comment]
`데이터바인딩` -> `뷰바인딩` 마이그레이션 진행하여 바인딩 어댑터 삭제 예정으로 이슈 닫음
